import time
import battles

a = 2
b = 3
c = 4
d = 5
e = 6
f = 7
g = 8
h = 9
i = 10


def chap0():
    print("Chapter 0:"
          "Prologue")
    time.sleep(c)
    print("You are awake in an unfamiliar room, without remembering the last place you were.")
    time.sleep(c)
    print("While lots of questions about your current status are appearing in your mind, ...")
    time.sleep(c)
    print("you decide to wake up from your bed.")
    time.sleep(b)
    print("On the table, you see a sword placed on it.")
    time.sleep(b)
    print("You are very fascinate with the sword's design due to its elegant and striking appearance...")
    time.sleep(c)
    print("That you decide to take and equip it.")
    time.sleep(b)
    print("After you equip the weapon, you realize that you are wearing a simple, white shirt and a short pants.")
    time.sleep(d)
    print("You proceed to see the window and it appears to be a wide field of grass waiting ahead of you.")
    time.sleep(d)
    print("Thinking that weird monsters will eventually appear and fight you, you decide to...")
    time.sleep(c)
    print("look for some armour.")
    time.sleep(a)
    print("After opening the wardrobe, you find a common, black armour.")
    time.sleep(b)
    print("Because you are cautious, you decide to wear that armour.")
    time.sleep(b)
    print("After some time for mental and physical preparations, you decide to venture out of the room.")
    time.sleep(c)
    print("\n" * 5)


def chap1():
    print("Chapter 1:"
          "Fateful encounter")
    time.sleep(c)
    print("As you step out from the room, you see a breathtaking scenery.")
    time.sleep(b)
    print("The air is so fresh that all your doubts were gone in a moment.")
    time.sleep(b)
    print("After enjoying the scenery for a moment, you are suddenly approached by a goblin named.")
    time.sleep(c)
    print("On its forehead, you see the word, 'Ecurb'.")
    time.sleep(a)
    print("probably implying the goblin's name.")
    time.sleep(a)
    print("You try to communicate with the goblin but it was useless.")
    time.sleep(b)
    print("Without further ado, you hold you sword and prepare to face the small creature!!!")
    time.sleep(c)
    print("\n" * 5)


def chap1_afterbattle():
    print("After a very intense battle with the goblin, you finally defeat it.")
    time.sleep(b)
    print("The goblin, fearing for its life, decides to run away.")
    time.sleep(a)
    print("Since you are now exhausted, you find a big tree and decide to rest under its shade.")
    time.sleep(c)
    print("You rest enough to proceed on you journey to find the mysteries of this world.")
    time.sleep(c)
    print("Suddenly, you hear a loud sound from the cliff near you.")
    time.sleep(b)
    print("You approach the cliff and found smoke in the forest.")
    time.sleep(a)
    print("To discover more mysteries in this world, you decide to continue into the forest.")
    time.sleep(c)
    print("\n" * 5)


def chap2():
    print("Chapter 2:"
          "Innocent encounter")
    time.sleep(c)
    print("You have reached the forest and proceed to look for any burnt tree.")
    time.sleep(b)
    print("No one answered and you decide to venture deeper into the forest, ...")
    time.sleep(b)
    print("In the midst of walking, you finally find the burning tree.")
    time.sleep(a)
    print("You check around the tree, but no one is there.")
    time.sleep(a)
    print("Suddenly, you find a trace of blood on the ground.")
    time.sleep(a)
    print("As you approach the trace of blood, you suddenly feel danger behind you.")
    time.sleep(b)
    print("When you turn around, an arrow just pass before your eyes, almost blinding you.")
    time.sleep(b)
    print("While panicking, you find an elf.")
    time.sleep(a)
    print("While aiming on you, you start to question her.")
    time.sleep(a)
    print("You: 'Who goes there?'")
    time.sleep(a)
    print("The elf instantly charges to attack you.")
    time.sleep(a)
    print("You prepare yourself and launch to battle her.")
    time.sleep(c)
    print("\n" * 5)


def chap2_afterbattle():
    print("As you approach the elf, her expression gets more terrified.")
    time.sleep(b)
    print("Knowing that she fears your outstanding skill and strength, you start to talk calmly with her.")
    time.sleep(d)
    print("You: 'I apologize for attacking you, I do not really mean to harm you.'")
    time.sleep(b)
    print("You: 'I was just trying to defend myself.'")
    time.sleep(b)
    print("Elf: 'Lies, you are preparing to deal the final blow!'")
    time.sleep(b)
    print("You: 'If I did, you would've died a second ago.'")
    time.sleep(b)
    print("After hearing your statement, she stopped panting and calmed down.")
    time.sleep(b)
    print("After hearing your statement, she stopped panting and calmed down.")
    time.sleep(b)
    print("Although you have amnesia, you somehow know that herbs can heal wounds.")
    time.sleep(b)
    print("You tried to search for herbs around you and found some nearby you.")
    time.sleep(b)
    print("The herb leaves that were gathered are folded into a form of coverings, and applied to the wounds.")
    time.sleep(d)
    print("You continue to converse with the elf")
    time.sleep(b)
    print("You: 'Since we have calmed down, do you mind if I ask your name?'")
    time.sleep(b)
    print("Elf: '...My name is Nairdirana.'")
    time.sleep(b)
    print("You: 'I see, nice to meet you. My name is-'")
    time.sleep(b)
    print("As you try to remember your name, you feel a very painful sensation in your head.")
    time.sleep(c)
    print("You: 'AAAAAAAAAAAAARRRRGGHHHHHHHHHHH'")
    time.sleep(a)
    print("As you feel the agonizing pain, the elf sings a hymn that somehow relieves you from the pain.")
    time.sleep(c)
    print("You proceed to talk to her.")
    time.sleep(a)
    print("You: 'Thank you very much for your help, if you were a second late i think my head could explode.'")
    time.sleep(d)
    print("Nairdirana: 'Don't mention it, I just suddenly felt an intuition to help you through singing my self-made"
          " hymn.'")
    time.sleep(d)
    print("You: 'I see, I'm sorry it seems that once I try to remember my name, that pain will trigger.'")
    time.sleep(d)
    print("Nairdirana: 'It is alright, I wonder what I will have to call you.'")
    time.sleep(b)
    print("You: 'How does Wanderer sound? I can't recall any memory from the moment i woke up this morning...")
    time.sleep(d)
    print("You: and i plan to know more about this world, through wandering around.'")
    time.sleep(c)
    print("Nairdirina: 'Sure, it really matches your current status, nice to be acquainted with you.'")
    time.sleep(d)
    print("You shake hands with Nairdirina, and she continues to talk with you.")
    time.sleep(b)
    print("Nairdirina: 'This place is unsafe, we should hurry to my village.'")
    time.sleep(b)
    print("You: 'Sure, lead the way.'")
    time.sleep(a)
    print("Together with Nairdirina, you continue to walk the path that she walked.")
    time.sleep(b)
    print("In the midst of walking, the ground shattered and a golem appeared from the ground.")
    time.sleep(c)
    print("Somehow, you cannot find her and the golem started attacking you.")
    time.sleep(b)
    print("You dodged the hit and proceed to fight the gigantic creature")
    time.sleep(c)
    print("\n" * 5)


def chap2_afterminibattle():
    print("In the midst of the chaos caused by the golem, you see an unconscious Nairdirina lying quite far from you.")
    time.sleep(c)
    print("You tried to reach and save her, but you instead fall deep underneath the ground.")
    time.sleep(c)
    print("In the midst of all the raining rocks, you keep falling...")
    time.sleep(c)
    print("into...")
    time.sleep(c)
    print("darkness...")
    time.sleep(c)
    print("\n" * 5)


def chap3():
    print("Chapter 3:"
          "Awakening")
    time.sleep(a)
    print("You finally wake up from a long slumber.")
    time.sleep(b)
    print("You surroundings turn out to be inside a cave.")
    time.sleep(b)
    print("Its very dark, but after walking for a moment, you found some rocks and a tree branch.")
    time.sleep(d)
    print("Somehow, you also have the knowledge of making a torch with stones.")
    time.sleep(b)
    print("With the power of knowledge, you made a torch and succeeded in making it.")
    time.sleep(b)
    print("Since you are in a cave, you assume that the golem has enough power to make... ")
    time.sleep(b)
    print("the ground it into a cave.")
    time.sleep(a)
    print("Forcing your way to climb up is suicidal, so you decide to take a detour and find the nearest exit.")
    time.sleep(d)
    print("As you find a way to the exit, you encounter two paths.")
    time.sleep(b)
    print("One path seems to slope up a little while the other path seems to slope down a bit.")
    time.sleep(d)
    print("Now, you must decide which path you will choose, the one sloping up or down?")
    time.sleep(c)
    print("""A. Sloping-up path\nB. Sloping-down path""")
    while True:
        choice = input("> ")
        if choice in ("a", "A", "Sloping-up path", "sloping-up path"):
            print("You decided to take the upwards path, the winding path up the cave starts to "
                  "become brighter and brighter")
            time.sleep(c)
            print("The brightness starts to get unbearable, not even your eyes can stand the blinding light.")
            time.sleep(b)
            print("As your eyes adjust to the light, your realize you are outside a cave, on a mountain slope.")
            time.sleep(b)
            print("You try to climb the mountain to its peak to assess the surrounding area.")
            time.sleep(b)
            print("As you climb higher up the mountain, the vegetation starts to thin out, and more "
                  "jagged rocks line your path.")
            time.sleep(c)
            print("suddenly as you climbed the hill, you see a sleeping white dragon.")
            time.sleep(b)
            print("Its eyes, as blue as the glamorous sapphires.")
            time.sleep(a)
            print("Spitting flames, Loud Roaring, A gust of wind from the beat of its 2 wings.")
            time.sleep(b)
            print("As you try to Flee, you were intercepted by the dragon, whose slumber was"
                  " disturbed, that's when you realize...")
            time.sleep(c)
            print("There is no escape!")
            time.sleep(c)
            print("\n" * 5)
            battles.battle_chap3A()
            print("You are now unable to move, and the dragon is inhaling to unleash a finishing attack.")
            time.sleep(c)
            print("Before doom comes, the dragon is suddenly struck by an arrow.")
            time.sleep(b)
            print("You turned around and found a party appearing behind you.")
            time.sleep(b)
            print("You are asked by a party member get farther from the dragon.")
            time.sleep(b)
            print("Party member 1: 'Out of the way! We got this, kid.'")
            time.sleep(b)
            print("You faced away from the dragon and hid behind a rock.")
            time.sleep(b)
            print("After some time, you hear a dying cry.")
            time.sleep(b)
            print("You try to peek from the tree to confirm the dragon's status.")
            time.sleep(b)
            print("It turns out the dragon's head is already decapitated and smashed to pieces.")
            time.sleep(c)
            print("As you are about to approach the party, you feel a loud grumbling.")
            time.sleep(c)
            print("Suddenly, a wurm appeared from the other side of the mountain.")
            time.sleep(c)
            print("A party member ordered you to go down the slope closest to you.")
            time.sleep(c)
            print("Party member 2: 'Run kid! We don't stand a chance against it.'")
            time.sleep(c)
            print("You immediately run down the slope and the party soon catches up after you with their horses.")
            time.sleep(d)
            print("A party member approaches you and reaches to you.")
            time.sleep(b)
            print("Party member 1: 'Ride on if you wanna live kid!'")
            time.sleep(b)
            print("You take his hand and sit behind him.")
            time.sleep(b)
            print("As you are fleeing for your life, you fell asleep behind him.")
            time.sleep(e)
            print("\n" * 5)
            break
        elif choice in ("b", "B", "Sloping-down path", "sloping-down path"):
            print("You decided to take the downwards path, the winding path down the cave starts to "
                  "become darker and darker")
            time.sleep(c)
            print("The darkness starts to get unbearable, not even your eyes can adjust to the darkness.")
            time.sleep(b)
            print("Within the pitch black road, you can hear small but subtle jeering from unseen figures.")
            time.sleep(b)
            print("The stalactites drips water around you, but you can't tell any way.")
            time.sleep(b)
            print("The cold dark suddenly became warmer and warmer, and the floor went from hard stone "
                  "to something soft.")
            time.sleep(d)
            print("A gust of strong wind fill the cave with a musty smell, the smell of carcasses and "
                  "rotting smell.")
            time.sleep(d)
            print("The jeering from these unseen figures grow louder and louder, the ground rumbled and "
                  "soon you loose footing.")
            time.sleep(d)
            print("The ground raises and you slip downwards into a wet cave, that's when you realized.")
            time.sleep(c)
            print("It's no cave, it's a wurm.")
            time.sleep(d)
            print("\n" * 5)
            battles.battle_chap3B()
            print("Although there is distance, the wurm still attempts to chase you.")
            time.sleep(c)
            print("You look back and you find a path that leads to a mountain.")
            time.sleep(c)
            print("Since fighting is now futile, you decide to climb up the mountain.")
            time.sleep(c)
            print("When you reach up the mountain, you find a dead dragon.")
            time.sleep(c)
            print("The dragon was horribly mutilated, parts of it were eaten by... something")
            time.sleep(c)
            print("You realize the danger and quickly trekked down the mountain.")
            time.sleep(c)
            print("As you kept running down the slope, a loud grumbling can be felt.")
            time.sleep(c)
            print("You passed by the party, only able to shout 'WURM!' before continuing the run.")
            time.sleep(c)
            print("Quickly, the party followed behind you as the wurm breaches through the earth, letting out a "
                  "bellowing roar.")
            time.sleep(d)
            print("You look behind as debris rains from the top of the wurm's head, as quickly as it inhaled the air "
                  "outside, the wurm returned down to the cave.")
            time.sleep(e)
            print("Party Member 1: 'WURM? WHY IS THERE A WURM HERE?!'")
            time.sleep(b)
            print("Wanderer: 'HOW SHOULD I KNOW, JUST KEEP RUNNING!'")
            time.sleep(b)
            print("The earth beneath you kept grumbling")
            time.sleep(b)
            print("Wanderer: 'Where's the nearest village?'")
            time.sleep(b)
            print("Party Member 2: 'Up north, its at least a few miles from here though.'")
            time.sleep(c)
            print("Wanderer: 'Anywhere else?'")
            time.sleep(a)
            print("Party Member 1: 'There really is nowhere else!'")
            time.sleep(b)
            print("Wanderer: 'Just go to that village, HURRY!'")
            time.sleep(b)
            print("Each of the party members whistle and horses come to each of them.")
            time.sleep(c)
            print("They hopped on their respective horses and a party member reaches his hand to you.")
            time.sleep(d)
            print("Party member 1: 'Ride on if you wanna live kid!'")
            time.sleep(b)
            print("You take his hand and sit behind him.")
            time.sleep(b)
            print("As you are fleeing for your life, you fell asleep behind him.")
            time.sleep(e)
            print("\n" * 5)
            break
        else:
            print("This is not a valid choice. Please input the answer from the choice given")




def chap4():
    print("Chapter 4:"
          "Advance")
    time.sleep(c)
    print("After a heavy, long slumber, you finally woke up to live another day.")
    time.sleep(b)
    print("Beside you is a priestess, who happens to be sleeping while her head is placed on the bed you’re "
          "sleeping on.")
    time.sleep(d)
    print("As you are about to wake her up by patting her head…")
    time.sleep(b)
    print(" she suddenly woke up by herself.")
    time.sleep(a)
    print("The priestess is now shocked and embarrassed, you can see her face turn red like a tomato.")
    time.sleep(c)
    print("Priestess: 'Ah! I am sorry to disturb your sleep.'")
    time.sleep(b)
    print("Priestess: 'I have been praying beside you all night long in hopes that you will recover.'")
    time.sleep(c)
    print("Wanderer: 'It is fine, I give my thanks for helping a stranger like me.'")
    time.sleep(b)
    print("Wanderer: 'Can you tell me more about where my location is.'")
    time.sleep(b)
    print("Priestess: 'Currently, you are being treated in the church of Nesyaj.'")
    time.sleep(b)
    print("Priestess: 'You were out for half a day, that battle with the wurm…")
    time.sleep(b)
    print("Priestess: must have taken a toll on you.'")
    time.sleep(a)
    print("Suddenly, you remember the party that saved your life from the wurm.")
    time.sleep(b)
    print("Wanderer: 'Wait, how are the party members that saved me?'")
    time.sleep(b)
    print("Priestess: 'Ah.. those adventurers. Relax, they are too experienced to be killed by a wurm.'")
    time.sleep(c)
    print("Wanderer: 'I see. I would feel guilty if something were to happen to them.'")
    time.sleep(b)
    print("Priestess: 'In fact, the swordsman has been asking for your condition…")
    time.sleep(b)
    print("Priestess: every hour yesterday.'")
    time.sleep(a)
    print("Priestess: 'Ah! I just remembered, the swordsman asked me to take you to him…")
    time.sleep(b)
    print("Priestess: after you’ve woken up.'")
    time.sleep(a)
    print("Priestess: 'He noticed that you are also using a sword, he wants to see your skills with the sword.'")
    time.sleep(c)
    print("Wanderer: 'I see, I shall humbly accept the offer then.'")
    time.sleep(b)
    print("Hearing your response, the priestess stands, bows down and leaves the room.")
    time.sleep(b)
    print("You looked towards the armour stand near the window and found a black armour with a greatsword nestled "
          "beside it in the stand.")
    time.sleep(d)
    print("On the table beside you, a note was left.")
    time.sleep(a)
    print("It says: 'Dear Stranger, If you are reading this message, I will be waiting…")
    time.sleep(b)
    print("in the Warrior’s Training Room. Due to your determination and bravery that you…")
    time.sleep(b)
    print("displayed, I decided to give you a new armour and a new sword.")
    time.sleep(b)
    print("The equipment supplied will help you prepare for the worst of your encounters.")
    time.sleep(b)
    print("If you still have any injuries, please do not force yourself and get more rest.")
    time.sleep(b)
    print("A fully healed body is crucial for improvement. And once again, welcome to Nesyaj Village.'")
    time.sleep(c)
    print("After you read the note, you wear the black armour and equip the greatsword.")
    time.sleep(b)
    print("You get ready to depart to the Warrior’s Training Room.")
    time.sleep(b)
    print("\n" * 5)
    print("Leaving the room, you find yourself in a lively village.")
    time.sleep(b)
    print("Merchants eagerly conduct their daily business, blacksmiths hammering weapons and the taverns are filled "
          "with fast, pumping songs.")
    time.sleep(d)
    print("After you admire the atmosphere of the village, you ask a merchant nearby for the location of the Warrior’s "
          "Training Room.")
    time.sleep(d)
    print("You have now learned the location of the Training Room.")
    time.sleep(b)
    print("Before you start your walk to your destination, the merchant gives you a loaf of bread.")
    time.sleep(c)
    print("You kindly accept and eat the bread. You feel energized.")
    time.sleep(b)
    print("You then proceed to walk to your destination.")
    time.sleep(b)
    print("In front of the training room, you see guards standing in front of the Training Room.")
    time.sleep(c)
    print("A Guard approaches you.")
    time.sleep(a)
    print("Guard: 'Halt! Please state your business, sir.'")
    time.sleep(b)
    print("Wanderer: 'I have an appointment with the Swordsman of the village watch.'")
    time.sleep(c)
    print("Guard: 'Ah, it is you. You are very fortunate that the Swordsman came just in time to rescue you.'")
    time.sleep(d)
    print("Guard: 'You are quite fortunate to be trained by Commander Langdorf.'")
    time.sleep(c)
    print("Wanderer: 'Wow, I never thought that he is so respected in this village.'")
    time.sleep(c)
    print("Wanderer: 'Now, if you’ll excuse me.'")
    time.sleep(b)
    print("Guard: 'Godspeed and may the winds of fortune guide you.'")
    time.sleep(c)
    print("\n" * 5)
    print("You enter the Training Room building and search for the Swordsman.")
    time.sleep(c)
    print("You notice that each room you pass is used to train different weapons.")
    time.sleep(c)
    print("It seems that a weapon master is appointed to every room.")
    time.sleep(c)
    print("As you are walking, you receive a hard slap from your back.")
    time.sleep(c)
    print("When you turn around, you finally find the Swordsman.")
    time.sleep(c)
    print("Commander Langdorf: 'It is good to see that you are back in shape lad.'")
    time.sleep(c)
    print("Commander Langdorf: 'Where are my manners?.'")
    time.sleep(b)
    print("Commander Langdorf: 'Greetings, the name is Langdorf. You?'")
    time.sleep(c)
    print("Wanderer: 'You can call me Wanderer. I am grateful for you and your friend’s rescue.'")
    time.sleep(c)
    print("Commander Langdorf: 'You’re welcome. By the way, how are your wounds?'")
    time.sleep(c)
    print("Wanderer: 'I feel healed and refreshed. Somehow, more energetic than before.'")
    time.sleep(c)
    print("Commander Langdorf: 'That is nice to hear, from your current condition, does this mean you are prepared "
          "to train?'")
    time.sleep(d)
    print("Wanderer: 'Ready, any time sir!'")
    time.sleep(a)
    print("Commander Langdorf: 'Anytime ey? THEN HOW ABOUT THIS!!!'")
    time.sleep(c)
    print("Commander Langdorf unleashes a heavy swing and you jump back.")
    time.sleep(b)
    print("Somehow, you enter a room with wooden swords hanging on the wall.")
    time.sleep(c)
    print("Commander Langdorf enters the room and moves into a stance.")
    time.sleep(c)
    print("You are fascinated by his form and you take out your greatsword and copy his stance.")
    time.sleep(c)
    print("Commander Langdorf: 'Well I'll be damned, you sure learn fast, young man. The real fight starts now! "
          "HUAAAAA!!!!'")
    time.sleep(d)
    print("Wanderer: *screams ORYAAAAA!!!!")
    time.sleep(d)
    print("\n" * 5)


def chap4_after_training():
    print("Commander Langdorf sheaths his sword and exhales a little.")
    time.sleep(b)
    print("Commander Langdorf: 'Pretty good for a beginner, a bit sloppy in techniques, but you got guts.'")
    time.sleep(d)
    print("You also sheath your sword.")
    time.sleep(a)
    print("Wanderer: 'Thanks, You give too much praise.'")
    time.sleep(b)
    print("Commander Langdorf: 'I mean it kid, I am a blunt person so believe in me.'")
    time.sleep(c)
    print("Commander Langdorf gives a light jab to Wanderer’s left shoulder.")
    time.sleep(c)
    print("Wanderer: 'If you say so, you are the commander after all.'")
    time.sleep(b)
    print("Commander Langdorf: ‘Now that’s the spirit. By the way, since you are a victim of the wurm’s...")
    time.sleep(d)
    print("assault, you will need to report to the guild, to testify about your encounter of that creature.’")
    time.sleep(d)
    print("Commander Langdorf: 'Recently, that wurm has been rampaging from village to village.'")
    time.sleep(c)
    print("Commander Langdorf: 'There is little information about its origin, but according to scholars, it...")
    time.sleep(d)
    print("originated from beneath the earth.'")
    time.sleep(b)
    print("Wanderer: 'Holy… That creature must be stopped at once.'")
    time.sleep(c)
    print("Commander Langdorf: 'Easy for you to say kid, dozens of my men have fallen victim to it.'")
    time.sleep(d)
    print("Commander Langdorf: 'I may look cruel but I can’t stand to see my precious subordinates gone.'")
    time.sleep(d)
    print("Wanderer: 'Hmmm, sorry to ask but, you have any plan if it attacks this village?'")
    time.sleep(c)
    print("Commander Langdorf: 'I have some ideas, but the village council still has other matter to take care of.'")
    time.sleep(d)
    print("“Wanderer: 'I see, let’s hope that this village will get prepared when the time comes.'")
    time.sleep(d)
    print("Commander Langdorf: 'Yes, let’s hope for the best.'")
    time.sleep(c)
    print("Commander Langdorf gives Wanderer a map to the guild.")
    time.sleep(c)
    print("Commander Langdorf turns around and bids farewell to Wanderer.")
    time.sleep(c)
    print("Wanderer bows to Commander Langdorf to give his gratitude and farewell.")
    time.sleep(c)
    print("\n" * 5)
    print("With the help of the map, Wanderer proceeds to walk to the Guild.")
    time.sleep(c)
    print("On the way to the guild, Wanderer passed through a dark alley.")
    time.sleep(c)
    print("As you are walking, you hear small footsteps and turn around to find that no one’s there.")
    time.sleep(d)
    print("Suddenly, you saw a dagger being placed on your throat.")
    time.sleep(c)
    print("The Mysterious Man: 'Shhh, you know I have the advantage, speak and you'll enter into eternal slumber.'")
    time.sleep(d)
    print("You quickly use your right foot to step on his right foot, releasing yourself from his arms, and draw "
          "your greatsword.")
    time.sleep(d)
    print("Wanderer: 'Reveal yourself, coward!'")
    time.sleep(b)
    print("The Mysterious Man: 'No can’t do, why would I do that?'")
    time.sleep(c)
    print("The Mysterious Man: 'The least I can do is tell you my name, it goes by Valorex.'")
    time.sleep(c)
    print("Valorex: 'I was intending for a ‘peaceful’ conversation, but it seems that blades speak louder than words.'")
    time.sleep(d)
    print("Wanderer: 'Fine by me. Let’s dance, this will be your last.'")
    time.sleep(c)
    print("Valorex: ‘May God smile when you arrive.’ *Indiscernible laughter")
    time.sleep(d)
    print("\n" * 5)







def chap4_after_valorex():
    print("Valorex: ‘There’s no fun in spoiling, tho. We’ll soon meet again, Eimarg.’")
    time.sleep(c)
    print("As soon as the smoke clears, Valorex’s traces have completely disappeared.")
    time.sleep(c)
    print("You try to remember your first memory, but it is always at the moment before you took the armour and sword.")
    time.sleep(d)
    print("You start to question your origin and purpose in life.")
    time.sleep(c)
    print("But you suddenly remember that you must report to the guild.")
    time.sleep(c)
    print("You walk to the guild, hoping to get more clues about your origin and this world.")
    time.sleep(c)
    print("As you keep on…")
    time.sleep(d)
    print("Wandering.")
    time.sleep(8)
    print("To be continued?")
    time.sleep(10)
    print("\n" * 5)
    print("The end.")


chap0()
chap1()
battles.battle_chap1()
chap1_afterbattle()
chap2()
battles.battle_chap2()
chap2_afterbattle()
battles.battle_chap2_1()
chap2_afterminibattle()
chap3()
chap4()
battles.battle_chap4_training()
chap4_after_training()
battles.battle_chap4_valorex()
chap4_after_valorex()
